# Generated by Django 4.1.5 on 2023-01-18 18:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id записи')),
                ('sender', models.CharField(max_length=255, verbose_name='Отправитель')),
                ('recipient', models.CharField(db_index=True, max_length=255, verbose_name='Получатель')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема письма')),
                ('body', models.TextField(blank=True, db_index=True, verbose_name='Содержание письма')),
                ('notification_status', models.CharField(default='QUEUED', max_length=255, verbose_name='Статус отправки')),
                ('sent_date', models.DateTimeField(null=True, verbose_name='Дата отправки')),
                ('last_error_date', models.DateTimeField(null=True, verbose_name='Дата ошибки при попытке отправить')),
                ('skipping', models.BooleanField(default=False, verbose_name='Игнорирование отправки')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Дата редактирования')),
                ('version', models.PositiveIntegerField(default=0, verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Email сообщение',
                'verbose_name_plural': 'Email сообщения',
                'db_table': 'notifier_app_email_notification',
                'ordering': ('created_date',),
            },
        ),
    ]
